import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { CORE_ENTITIES } from '../src/entities';
import { policyExpression, type Operation } from '../src/rls';

/**
 * Turns the declared matrix into the SQL that is actually applied.
 *
 * Generated rather than hand-written so the policy in the database and the
 * policy in `rls.ts` cannot drift. `rls.db.test.ts` reads the live policies
 * back and compares them to this output, so a matrix edit that was never
 * regenerated fails the suite.
 *
 *   npx tsx packages/shared-db/scripts/generate-rls.ts
 */

const OPERATIONS: Operation[] = ['select', 'insert', 'update', 'delete'];
const APP_ROLE = 'qhakaza_app';

const lines: string[] = [
  '-- Phase 5 - Row-Level Security.',
  '--',
  '-- GENERATED by packages/shared-db/scripts/generate-rls.ts from RLS_MATRIX.',
  '-- Do not hand-edit: regenerate instead, or the drift test will fail.',
  '--',
  '-- Non-destructive: creates a role, grants, and policies. No DROP of any',
  '-- table or column, no DELETE of any row.',
  '',
  '-- The application role. NOSUPERUSER and no BYPASSRLS is the entire point:',
  '-- the owner (qhakaza) keeps ownership and continues to run migrations,',
  '-- while the apps connect as a role that policies actually constrain.',
  'DO $$',
  'BEGIN',
  `  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_ROLE}') THEN`,
  `    CREATE ROLE ${APP_ROLE} LOGIN PASSWORD 'qhakaza_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;`,
  '  END IF;',
  'END $$;',
  '',
  `GRANT USAGE ON SCHEMA public TO ${APP_ROLE};`,
  `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_ROLE};`,
  `GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${APP_ROLE};`,
  '-- Tables added later are covered without another grant.',
  `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_ROLE};`,
  '',
];

for (const entity of CORE_ENTITIES) {
  lines.push(
    `-- ${'-'.repeat(70)}`,
    `-- ${entity}`,
    `-- ${'-'.repeat(70)}`,
    `ALTER TABLE "${entity}" ENABLE ROW LEVEL SECURITY;`,
    '',
  );

  for (const operation of OPERATIONS) {
    const name = `${entity.toLowerCase()}_${operation}`;
    const expression = policyExpression(entity, operation);

    lines.push(`DROP POLICY IF EXISTS "${name}" ON "${entity}";`);

    if (expression === null) {
      // No role is granted this operation. A policy with USING (false) is
      // clearer than no policy at all: "deny" is stated, not merely implied by
      // absence, and it shows up when the policies are listed.
      lines.push(
        operation === 'insert'
          ? `CREATE POLICY "${name}" ON "${entity}" FOR INSERT WITH CHECK (false);`
          : `CREATE POLICY "${name}" ON "${entity}" FOR ${operation.toUpperCase()} USING (false);`,
        '',
      );
      continue;
    }

    if (operation === 'insert') {
      lines.push(
        `CREATE POLICY "${name}" ON "${entity}" FOR INSERT WITH CHECK (\n      ${expression}\n);`,
        '',
      );
    } else if (operation === 'update') {
      // USING decides which rows may be updated; WITH CHECK decides what they
      // may become. Without the second, a permitted row could be edited into
      // one the actor was never allowed to touch.
      lines.push(
        `CREATE POLICY "${name}" ON "${entity}" FOR UPDATE USING (\n      ${expression}\n) WITH CHECK (\n      ${expression}\n);`,
        '',
      );
    } else {
      lines.push(
        `CREATE POLICY "${name}" ON "${entity}" FOR ${operation.toUpperCase()} USING (\n      ${expression}\n);`,
        '',
      );
    }
  }
}

// The generated SQL is idempotent (DROP POLICY IF EXISTS before each CREATE),
// so regenerating into a new migration folder re-applies the whole matrix
// cleanly rather than requiring the previous migration to be edited in place.
const name = process.argv[2] ?? '20260805000000_row_level_security';
const target = resolve(import.meta.dirname, `../prisma/migrations/${name}/migration.sql`);

writeFileSync(target, lines.join('\n'), 'utf8');
console.log(`wrote ${target}`);
console.log(
  `${CORE_ENTITIES.length} entities, ${CORE_ENTITIES.length * OPERATIONS.length} policies`,
);
