-- Phase 5 - Row-Level Security.
--
-- GENERATED by packages/shared-db/scripts/generate-rls.ts from RLS_MATRIX.
-- Do not hand-edit: regenerate instead, or the drift test will fail.
--
-- Non-destructive: creates a role, grants, and policies. No DROP of any
-- table or column, no DELETE of any row.

-- The application role. NOSUPERUSER and no BYPASSRLS is the entire point:
-- the owner (qhakaza) keeps ownership and continues to run migrations,
-- while the apps connect as a role that policies actually constrain.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qhakaza_app') THEN
    CREATE ROLE qhakaza_app LOGIN PASSWORD 'qhakaza_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO qhakaza_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO qhakaza_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO qhakaza_app;
-- Tables added later are covered without another grant.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qhakaza_app;

-- ----------------------------------------------------------------------
-- Membership
-- ----------------------------------------------------------------------
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "membership_select" ON "Membership";
CREATE POLICY "membership_select" ON "Membership" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "membership_insert" ON "Membership";
CREATE POLICY "membership_insert" ON "Membership" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "membership_update" ON "Membership";
CREATE POLICY "membership_update" ON "Membership" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "membership_delete" ON "Membership";
CREATE POLICY "membership_delete" ON "Membership" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- CollectorIntake
-- ----------------------------------------------------------------------
ALTER TABLE "CollectorIntake" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "collectorintake_select" ON "CollectorIntake";
CREATE POLICY "collectorintake_select" ON "CollectorIntake" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorintake_insert" ON "CollectorIntake";
CREATE POLICY "collectorintake_insert" ON "CollectorIntake" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public'
);

DROP POLICY IF EXISTS "collectorintake_update" ON "CollectorIntake";
CREATE POLICY "collectorintake_update" ON "CollectorIntake" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorintake_delete" ON "CollectorIntake";
CREATE POLICY "collectorintake_delete" ON "CollectorIntake" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CollectorVerification
-- ----------------------------------------------------------------------
ALTER TABLE "CollectorVerification" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "collectorverification_select" ON "CollectorVerification";
CREATE POLICY "collectorverification_select" ON "CollectorVerification" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_insert" ON "CollectorVerification";
CREATE POLICY "collectorverification_insert" ON "CollectorVerification" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_update" ON "CollectorVerification";
CREATE POLICY "collectorverification_update" ON "CollectorVerification" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_delete" ON "CollectorVerification";
CREATE POLICY "collectorverification_delete" ON "CollectorVerification" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- MemberInvitation
-- ----------------------------------------------------------------------
ALTER TABLE "MemberInvitation" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "memberinvitation_select" ON "MemberInvitation";
CREATE POLICY "memberinvitation_select" ON "MemberInvitation" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "memberinvitation_insert" ON "MemberInvitation";
CREATE POLICY "memberinvitation_insert" ON "MemberInvitation" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "memberinvitation_update" ON "MemberInvitation";
CREATE POLICY "memberinvitation_update" ON "MemberInvitation" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "memberinvitation_delete" ON "MemberInvitation";
CREATE POLICY "memberinvitation_delete" ON "MemberInvitation" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- InvitationRecipientType
-- ----------------------------------------------------------------------
ALTER TABLE "InvitationRecipientType" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "invitationrecipienttype_select" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_select" ON "InvitationRecipientType" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "invitationrecipienttype_insert" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_insert" ON "InvitationRecipientType" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "invitationrecipienttype_update" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_update" ON "InvitationRecipientType" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "invitationrecipienttype_delete" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_delete" ON "InvitationRecipientType" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Artist
-- ----------------------------------------------------------------------
ALTER TABLE "Artist" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artist_select" ON "Artist";
CREATE POLICY "artist_select" ON "Artist" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("approved" = true))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("approved" = true))
);

DROP POLICY IF EXISTS "artist_insert" ON "Artist";
CREATE POLICY "artist_insert" ON "Artist" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "artist_update" ON "Artist";
CREATE POLICY "artist_update" ON "Artist" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "artist_delete" ON "Artist";
CREATE POLICY "artist_delete" ON "Artist" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- Artwork
-- ----------------------------------------------------------------------
ALTER TABLE "Artwork" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artwork_select" ON "Artwork";
CREATE POLICY "artwork_select" ON "Artwork" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("status" = 'LISTED' AND "artistId" IN (SELECT "id" FROM "Artist" WHERE "approved" = true)))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("status" = 'LISTED' AND "artistId" IN (SELECT "id" FROM "Artist" WHERE "approved" = true)))
);

DROP POLICY IF EXISTS "artwork_insert" ON "Artwork";
CREATE POLICY "artwork_insert" ON "Artwork" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "artwork_update" ON "Artwork";
CREATE POLICY "artwork_update" ON "Artwork" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "artwork_delete" ON "Artwork";
CREATE POLICY "artwork_delete" ON "Artwork" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- NewsArticle
-- ----------------------------------------------------------------------
ALTER TABLE "NewsArticle" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "newsarticle_select" ON "NewsArticle";
CREATE POLICY "newsarticle_select" ON "NewsArticle" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("status" = 'PUBLISHED'))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("status" = 'PUBLISHED'))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("status" = 'PUBLISHED'))
);

DROP POLICY IF EXISTS "newsarticle_insert" ON "NewsArticle";
CREATE POLICY "newsarticle_insert" ON "NewsArticle" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "newsarticle_update" ON "NewsArticle";
CREATE POLICY "newsarticle_update" ON "NewsArticle" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "newsarticle_delete" ON "NewsArticle";
CREATE POLICY "newsarticle_delete" ON "NewsArticle" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- PrivateNoteSubmission
-- ----------------------------------------------------------------------
ALTER TABLE "PrivateNoteSubmission" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "privatenotesubmission_select" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_select" ON "PrivateNoteSubmission" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("membershipId" IN (SELECT "id" FROM "Membership" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "privatenotesubmission_insert" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_insert" ON "PrivateNoteSubmission" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
);

DROP POLICY IF EXISTS "privatenotesubmission_update" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_update" ON "PrivateNoteSubmission" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "privatenotesubmission_delete" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_delete" ON "PrivateNoteSubmission" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- AnalyticsEvent
-- ----------------------------------------------------------------------
ALTER TABLE "AnalyticsEvent" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analyticsevent_select" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_select" ON "AnalyticsEvent" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "analyticsevent_insert" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_insert" ON "AnalyticsEvent" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public'
);

DROP POLICY IF EXISTS "analyticsevent_update" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_update" ON "AnalyticsEvent" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "analyticsevent_delete" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_delete" ON "AnalyticsEvent" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- DailyMetric
-- ----------------------------------------------------------------------
ALTER TABLE "DailyMetric" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dailymetric_select" ON "DailyMetric";
CREATE POLICY "dailymetric_select" ON "DailyMetric" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "dailymetric_insert" ON "DailyMetric";
CREATE POLICY "dailymetric_insert" ON "DailyMetric" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "dailymetric_update" ON "DailyMetric";
CREATE POLICY "dailymetric_update" ON "DailyMetric" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "dailymetric_delete" ON "DailyMetric";
CREATE POLICY "dailymetric_delete" ON "DailyMetric" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- AuditLog
-- ----------------------------------------------------------------------
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auditlog_select" ON "AuditLog";
CREATE POLICY "auditlog_select" ON "AuditLog" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "auditlog_insert" ON "AuditLog";
CREATE POLICY "auditlog_insert" ON "AuditLog" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "auditlog_update" ON "AuditLog";
CREATE POLICY "auditlog_update" ON "AuditLog" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "auditlog_delete" ON "AuditLog";
CREATE POLICY "auditlog_delete" ON "AuditLog" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ActivationAttempt
-- ----------------------------------------------------------------------
ALTER TABLE "ActivationAttempt" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activationattempt_select" ON "ActivationAttempt";
CREATE POLICY "activationattempt_select" ON "ActivationAttempt" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "activationattempt_insert" ON "ActivationAttempt";
CREATE POLICY "activationattempt_insert" ON "ActivationAttempt" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "activationattempt_update" ON "ActivationAttempt";
CREATE POLICY "activationattempt_update" ON "ActivationAttempt" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "activationattempt_delete" ON "ActivationAttempt";
CREATE POLICY "activationattempt_delete" ON "ActivationAttempt" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Partner
-- ----------------------------------------------------------------------
ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "partner_select" ON "Partner";
CREATE POLICY "partner_select" ON "Partner" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "partner_insert" ON "Partner";
CREATE POLICY "partner_insert" ON "Partner" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partner_update" ON "Partner";
CREATE POLICY "partner_update" ON "Partner" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partner_delete" ON "Partner";
CREATE POLICY "partner_delete" ON "Partner" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);
