-- Phase 1 follow-up: align index names with the mapped column names.
--
-- Generated by `prisma migrate diff`. 21 ALTER INDEX ... RENAME statements and
-- nothing else -- verified free of DROP, DELETE and TRUNCATE before applying.
-- Prisma derives index names from column names, so mapping createdAt to
-- created_date renamed the indexes too.

-- RenameIndex
ALTER INDEX "ActivationAttempt_createdById_idx" RENAME TO "ActivationAttempt_created_by_id_idx";

-- RenameIndex
ALTER INDEX "ActivationAttempt_outcome_createdAt_idx" RENAME TO "ActivationAttempt_outcome_created_date_idx";

-- RenameIndex
ALTER INDEX "AnalyticsEvent_createdById_idx" RENAME TO "AnalyticsEvent_created_by_id_idx";

-- RenameIndex
ALTER INDEX "Artist_createdById_idx" RENAME TO "Artist_created_by_id_idx";

-- RenameIndex
ALTER INDEX "Artwork_createdById_idx" RENAME TO "Artwork_created_by_id_idx";

-- RenameIndex
ALTER INDEX "AuditLog_action_createdAt_idx" RENAME TO "AuditLog_action_created_date_idx";

-- RenameIndex
ALTER INDEX "AuditLog_actorId_createdAt_idx" RENAME TO "AuditLog_actorId_created_date_idx";

-- RenameIndex
ALTER INDEX "AuditLog_createdById_idx" RENAME TO "AuditLog_created_by_id_idx";

-- RenameIndex
ALTER INDEX "CollectorIntake_createdById_idx" RENAME TO "CollectorIntake_created_by_id_idx";

-- RenameIndex
ALTER INDEX "CollectorIntake_status_createdAt_idx" RENAME TO "CollectorIntake_status_created_date_idx";

-- RenameIndex
ALTER INDEX "CollectorVerification_createdById_idx" RENAME TO "CollectorVerification_created_by_id_idx";

-- RenameIndex
ALTER INDEX "ContactMessage_handled_createdAt_idx" RENAME TO "ContactMessage_handled_created_date_idx";

-- RenameIndex
ALTER INDEX "DailyMetric_createdById_idx" RENAME TO "DailyMetric_created_by_id_idx";

-- RenameIndex
ALTER INDEX "MemberInvitation_createdById_idx" RENAME TO "MemberInvitation_created_by_id_idx";

-- RenameIndex
ALTER INDEX "Membership_createdById_idx" RENAME TO "Membership_created_by_id_idx";

-- RenameIndex
ALTER INDEX "NewsArticle_createdById_idx" RENAME TO "NewsArticle_created_by_id_idx";

-- RenameIndex
ALTER INDEX "Order_createdById_idx" RENAME TO "Order_created_by_id_idx";

-- RenameIndex
ALTER INDEX "Partner_createdById_idx" RENAME TO "Partner_created_by_id_idx";

-- RenameIndex
ALTER INDEX "PrivateNoteSubmission_createdById_idx" RENAME TO "PrivateNoteSubmission_created_by_id_idx";

-- RenameIndex
ALTER INDEX "PrivateNoteSubmission_status_createdAt_idx" RENAME TO "PrivateNoteSubmission_status_created_date_idx";

-- RenameIndex
ALTER INDEX "User_createdById_idx" RENAME TO "User_created_by_id_idx";

