-- Phase 5 - Row-Level Security.
--
-- GENERATED by packages/shared-db/scripts/generate-rls.ts from RLS_MATRIX.
-- Do not hand-edit: regenerate instead, or the drift test will fail.
--
-- Non-destructive: creates a role, grants, and policies. No DROP of any
-- table or column, no DELETE of any row.

-- The application role. NOSUPERUSER and no BYPASSRLS is the entire point:
-- the owner (qhakaza) keeps ownership and continues to run migrations,
-- while the apps connect as a role that policies actually constrain.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'qhakaza_app') THEN
    CREATE ROLE qhakaza_app LOGIN PASSWORD 'qhakaza_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO qhakaza_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO qhakaza_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO qhakaza_app;
-- Tables added later are covered without another grant.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO qhakaza_app;

-- ----------------------------------------------------------------------
-- Membership
-- ----------------------------------------------------------------------
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "membership_select" ON "Membership";
CREATE POLICY "membership_select" ON "Membership" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "membership_insert" ON "Membership";
CREATE POLICY "membership_insert" ON "Membership" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "membership_update" ON "Membership";
CREATE POLICY "membership_update" ON "Membership" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "membership_delete" ON "Membership";
CREATE POLICY "membership_delete" ON "Membership" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- CollectorIntake
-- ----------------------------------------------------------------------
ALTER TABLE "CollectorIntake" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "collectorintake_select" ON "CollectorIntake";
CREATE POLICY "collectorintake_select" ON "CollectorIntake" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorintake_insert" ON "CollectorIntake";
CREATE POLICY "collectorintake_insert" ON "CollectorIntake" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public'
);

DROP POLICY IF EXISTS "collectorintake_update" ON "CollectorIntake";
CREATE POLICY "collectorintake_update" ON "CollectorIntake" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorintake_delete" ON "CollectorIntake";
CREATE POLICY "collectorintake_delete" ON "CollectorIntake" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CollectorVerification
-- ----------------------------------------------------------------------
ALTER TABLE "CollectorVerification" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "collectorverification_select" ON "CollectorVerification";
CREATE POLICY "collectorverification_select" ON "CollectorVerification" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_insert" ON "CollectorVerification";
CREATE POLICY "collectorverification_insert" ON "CollectorVerification" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_update" ON "CollectorVerification";
CREATE POLICY "collectorverification_update" ON "CollectorVerification" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "collectorverification_delete" ON "CollectorVerification";
CREATE POLICY "collectorverification_delete" ON "CollectorVerification" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- MemberInvitation
-- ----------------------------------------------------------------------
ALTER TABLE "MemberInvitation" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "memberinvitation_select" ON "MemberInvitation";
CREATE POLICY "memberinvitation_select" ON "MemberInvitation" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "memberinvitation_insert" ON "MemberInvitation";
CREATE POLICY "memberinvitation_insert" ON "MemberInvitation" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "memberinvitation_update" ON "MemberInvitation";
CREATE POLICY "memberinvitation_update" ON "MemberInvitation" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "memberinvitation_delete" ON "MemberInvitation";
CREATE POLICY "memberinvitation_delete" ON "MemberInvitation" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- InvitationRecipientType
-- ----------------------------------------------------------------------
ALTER TABLE "InvitationRecipientType" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "invitationrecipienttype_select" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_select" ON "InvitationRecipientType" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "invitationrecipienttype_insert" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_insert" ON "InvitationRecipientType" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "invitationrecipienttype_update" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_update" ON "InvitationRecipientType" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "invitationrecipienttype_delete" ON "InvitationRecipientType";
CREATE POLICY "invitationrecipienttype_delete" ON "InvitationRecipientType" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- MediaAsset
-- ----------------------------------------------------------------------
ALTER TABLE "MediaAsset" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "mediaasset_select" ON "MediaAsset";
CREATE POLICY "mediaasset_select" ON "MediaAsset" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
);

DROP POLICY IF EXISTS "mediaasset_insert" ON "MediaAsset";
CREATE POLICY "mediaasset_insert" ON "MediaAsset" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
);

DROP POLICY IF EXISTS "mediaasset_update" ON "MediaAsset";
CREATE POLICY "mediaasset_update" ON "MediaAsset" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
);

DROP POLICY IF EXISTS "mediaasset_delete" ON "MediaAsset";
CREATE POLICY "mediaasset_delete" ON "MediaAsset" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- InternalNote
-- ----------------------------------------------------------------------
ALTER TABLE "InternalNote" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "internalnote_select" ON "InternalNote";
CREATE POLICY "internalnote_select" ON "InternalNote" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "internalnote_insert" ON "InternalNote";
CREATE POLICY "internalnote_insert" ON "InternalNote" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "internalnote_update" ON "InternalNote";
CREATE POLICY "internalnote_update" ON "InternalNote" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "internalnote_delete" ON "InternalNote";
CREATE POLICY "internalnote_delete" ON "InternalNote" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- InternalNoteRevision
-- ----------------------------------------------------------------------
ALTER TABLE "InternalNoteRevision" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "internalnoterevision_select" ON "InternalNoteRevision";
CREATE POLICY "internalnoterevision_select" ON "InternalNoteRevision" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "internalnoterevision_insert" ON "InternalNoteRevision";
CREATE POLICY "internalnoterevision_insert" ON "InternalNoteRevision" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "internalnoterevision_update" ON "InternalNoteRevision";
CREATE POLICY "internalnoterevision_update" ON "InternalNoteRevision" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "internalnoterevision_delete" ON "InternalNoteRevision";
CREATE POLICY "internalnoterevision_delete" ON "InternalNoteRevision" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ArtworkReviewRequest
-- ----------------------------------------------------------------------
ALTER TABLE "ArtworkReviewRequest" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artworkreviewrequest_select" ON "ArtworkReviewRequest";
CREATE POLICY "artworkreviewrequest_select" ON "ArtworkReviewRequest" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
);

DROP POLICY IF EXISTS "artworkreviewrequest_insert" ON "ArtworkReviewRequest";
CREATE POLICY "artworkreviewrequest_insert" ON "ArtworkReviewRequest" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "artworkreviewrequest_update" ON "ArtworkReviewRequest";
CREATE POLICY "artworkreviewrequest_update" ON "ArtworkReviewRequest" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "artworkreviewrequest_delete" ON "ArtworkReviewRequest";
CREATE POLICY "artworkreviewrequest_delete" ON "ArtworkReviewRequest" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- EvidenceType
-- ----------------------------------------------------------------------
ALTER TABLE "EvidenceType" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "evidencetype_select" ON "EvidenceType";
CREATE POLICY "evidencetype_select" ON "EvidenceType" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidencetype_insert" ON "EvidenceType";
CREATE POLICY "evidencetype_insert" ON "EvidenceType" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "evidencetype_update" ON "EvidenceType";
CREATE POLICY "evidencetype_update" ON "EvidenceType" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "evidencetype_delete" ON "EvidenceType";
CREATE POLICY "evidencetype_delete" ON "EvidenceType" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ReliabilityLevel
-- ----------------------------------------------------------------------
ALTER TABLE "ReliabilityLevel" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reliabilitylevel_select" ON "ReliabilityLevel";
CREATE POLICY "reliabilitylevel_select" ON "ReliabilityLevel" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "reliabilitylevel_insert" ON "ReliabilityLevel";
CREATE POLICY "reliabilitylevel_insert" ON "ReliabilityLevel" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "reliabilitylevel_update" ON "ReliabilityLevel";
CREATE POLICY "reliabilitylevel_update" ON "ReliabilityLevel" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "reliabilitylevel_delete" ON "ReliabilityLevel";
CREATE POLICY "reliabilitylevel_delete" ON "ReliabilityLevel" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- GapType
-- ----------------------------------------------------------------------
ALTER TABLE "GapType" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "gaptype_select" ON "GapType";
CREATE POLICY "gaptype_select" ON "GapType" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "gaptype_insert" ON "GapType";
CREATE POLICY "gaptype_insert" ON "GapType" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "gaptype_update" ON "GapType";
CREATE POLICY "gaptype_update" ON "GapType" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "gaptype_delete" ON "GapType";
CREATE POLICY "gaptype_delete" ON "GapType" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- SpecialistCategory
-- ----------------------------------------------------------------------
ALTER TABLE "SpecialistCategory" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "specialistcategory_select" ON "SpecialistCategory";
CREATE POLICY "specialistcategory_select" ON "SpecialistCategory" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "specialistcategory_insert" ON "SpecialistCategory";
CREATE POLICY "specialistcategory_insert" ON "SpecialistCategory" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "specialistcategory_update" ON "SpecialistCategory";
CREATE POLICY "specialistcategory_update" ON "SpecialistCategory" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "specialistcategory_delete" ON "SpecialistCategory";
CREATE POLICY "specialistcategory_delete" ON "SpecialistCategory" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- PartyRole
-- ----------------------------------------------------------------------
ALTER TABLE "PartyRole" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "partyrole_select" ON "PartyRole";
CREATE POLICY "partyrole_select" ON "PartyRole" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "partyrole_insert" ON "PartyRole";
CREATE POLICY "partyrole_insert" ON "PartyRole" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partyrole_update" ON "PartyRole";
CREATE POLICY "partyrole_update" ON "PartyRole" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partyrole_delete" ON "PartyRole";
CREATE POLICY "partyrole_delete" ON "PartyRole" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Party
-- ----------------------------------------------------------------------
ALTER TABLE "Party" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "party_select" ON "Party";
CREATE POLICY "party_select" ON "Party" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "party_insert" ON "Party";
CREATE POLICY "party_insert" ON "Party" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "party_update" ON "Party";
CREATE POLICY "party_update" ON "Party" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "party_delete" ON "Party";
CREATE POLICY "party_delete" ON "Party" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Exhibition
-- ----------------------------------------------------------------------
ALTER TABLE "Exhibition" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "exhibition_select" ON "Exhibition";
CREATE POLICY "exhibition_select" ON "Exhibition" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "exhibition_insert" ON "Exhibition";
CREATE POLICY "exhibition_insert" ON "Exhibition" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "exhibition_update" ON "Exhibition";
CREATE POLICY "exhibition_update" ON "Exhibition" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "exhibition_delete" ON "Exhibition";
CREATE POLICY "exhibition_delete" ON "Exhibition" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Publication
-- ----------------------------------------------------------------------
ALTER TABLE "Publication" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "publication_select" ON "Publication";
CREATE POLICY "publication_select" ON "Publication" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "publication_insert" ON "Publication";
CREATE POLICY "publication_insert" ON "Publication" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "publication_update" ON "Publication";
CREATE POLICY "publication_update" ON "Publication" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "publication_delete" ON "Publication";
CREATE POLICY "publication_delete" ON "Publication" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ProvenanceTransaction
-- ----------------------------------------------------------------------
ALTER TABLE "ProvenanceTransaction" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "provenancetransaction_select" ON "ProvenanceTransaction";
CREATE POLICY "provenancetransaction_select" ON "ProvenanceTransaction" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "provenancetransaction_insert" ON "ProvenanceTransaction";
CREATE POLICY "provenancetransaction_insert" ON "ProvenanceTransaction" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "provenancetransaction_update" ON "ProvenanceTransaction";
CREATE POLICY "provenancetransaction_update" ON "ProvenanceTransaction" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "provenancetransaction_delete" ON "ProvenanceTransaction";
CREATE POLICY "provenancetransaction_delete" ON "ProvenanceTransaction" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Source
-- ----------------------------------------------------------------------
ALTER TABLE "Source" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "source_select" ON "Source";
CREATE POLICY "source_select" ON "Source" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "source_insert" ON "Source";
CREATE POLICY "source_insert" ON "Source" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "source_update" ON "Source";
CREATE POLICY "source_update" ON "Source" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "source_delete" ON "Source";
CREATE POLICY "source_delete" ON "Source" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Evidence
-- ----------------------------------------------------------------------
ALTER TABLE "Evidence" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "evidence_select" ON "Evidence";
CREATE POLICY "evidence_select" ON "Evidence" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidence_insert" ON "Evidence";
CREATE POLICY "evidence_insert" ON "Evidence" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidence_update" ON "Evidence";
CREATE POLICY "evidence_update" ON "Evidence" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidence_delete" ON "Evidence";
CREATE POLICY "evidence_delete" ON "Evidence" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Claim
-- ----------------------------------------------------------------------
ALTER TABLE "Claim" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "claim_select" ON "Claim";
CREATE POLICY "claim_select" ON "Claim" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claim_insert" ON "Claim";
CREATE POLICY "claim_insert" ON "Claim" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claim_update" ON "Claim";
CREATE POLICY "claim_update" ON "Claim" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claim_delete" ON "Claim";
CREATE POLICY "claim_delete" ON "Claim" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Assessment
-- ----------------------------------------------------------------------
ALTER TABLE "Assessment" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "assessment_select" ON "Assessment";
CREATE POLICY "assessment_select" ON "Assessment" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "assessment_insert" ON "Assessment";
CREATE POLICY "assessment_insert" ON "Assessment" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "assessment_update" ON "Assessment";
CREATE POLICY "assessment_update" ON "Assessment" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "assessment_delete" ON "Assessment";
CREATE POLICY "assessment_delete" ON "Assessment" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Gap
-- ----------------------------------------------------------------------
ALTER TABLE "Gap" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "gap_select" ON "Gap";
CREATE POLICY "gap_select" ON "Gap" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "gap_insert" ON "Gap";
CREATE POLICY "gap_insert" ON "Gap" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "gap_update" ON "Gap";
CREATE POLICY "gap_update" ON "Gap" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "gap_delete" ON "Gap";
CREATE POLICY "gap_delete" ON "Gap" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Contradiction
-- ----------------------------------------------------------------------
ALTER TABLE "Contradiction" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contradiction_select" ON "Contradiction";
CREATE POLICY "contradiction_select" ON "Contradiction" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "contradiction_insert" ON "Contradiction";
CREATE POLICY "contradiction_insert" ON "Contradiction" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "contradiction_update" ON "Contradiction";
CREATE POLICY "contradiction_update" ON "Contradiction" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "contradiction_delete" ON "Contradiction";
CREATE POLICY "contradiction_delete" ON "Contradiction" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- SpecialistEscalation
-- ----------------------------------------------------------------------
ALTER TABLE "SpecialistEscalation" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "specialistescalation_select" ON "SpecialistEscalation";
CREATE POLICY "specialistescalation_select" ON "SpecialistEscalation" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "specialistescalation_insert" ON "SpecialistEscalation";
CREATE POLICY "specialistescalation_insert" ON "SpecialistEscalation" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "specialistescalation_update" ON "SpecialistEscalation";
CREATE POLICY "specialistescalation_update" ON "SpecialistEscalation" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "specialistescalation_delete" ON "SpecialistEscalation";
CREATE POLICY "specialistescalation_delete" ON "SpecialistEscalation" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- MethodologyVersion
-- ----------------------------------------------------------------------
ALTER TABLE "MethodologyVersion" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "methodologyversion_select" ON "MethodologyVersion";
CREATE POLICY "methodologyversion_select" ON "MethodologyVersion" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "methodologyversion_insert" ON "MethodologyVersion";
CREATE POLICY "methodologyversion_insert" ON "MethodologyVersion" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "methodologyversion_update" ON "MethodologyVersion";
CREATE POLICY "methodologyversion_update" ON "MethodologyVersion" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "methodologyversion_delete" ON "MethodologyVersion";
CREATE POLICY "methodologyversion_delete" ON "MethodologyVersion" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- IntelligenceCase
-- ----------------------------------------------------------------------
ALTER TABLE "IntelligenceCase" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "intelligencecase_select" ON "IntelligenceCase";
CREATE POLICY "intelligencecase_select" ON "IntelligenceCase" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "intelligencecase_insert" ON "IntelligenceCase";
CREATE POLICY "intelligencecase_insert" ON "IntelligenceCase" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "intelligencecase_update" ON "IntelligenceCase";
CREATE POLICY "intelligencecase_update" ON "IntelligenceCase" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "intelligencecase_delete" ON "IntelligenceCase";
CREATE POLICY "intelligencecase_delete" ON "IntelligenceCase" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CaseVersion
-- ----------------------------------------------------------------------
ALTER TABLE "CaseVersion" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "caseversion_select" ON "CaseVersion";
CREATE POLICY "caseversion_select" ON "CaseVersion" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseversion_insert" ON "CaseVersion";
CREATE POLICY "caseversion_insert" ON "CaseVersion" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseversion_update" ON "CaseVersion";
CREATE POLICY "caseversion_update" ON "CaseVersion" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "caseversion_delete" ON "CaseVersion";
CREATE POLICY "caseversion_delete" ON "CaseVersion" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CaseArtwork
-- ----------------------------------------------------------------------
ALTER TABLE "CaseArtwork" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "caseartwork_select" ON "CaseArtwork";
CREATE POLICY "caseartwork_select" ON "CaseArtwork" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseartwork_insert" ON "CaseArtwork";
CREATE POLICY "caseartwork_insert" ON "CaseArtwork" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseartwork_update" ON "CaseArtwork";
CREATE POLICY "caseartwork_update" ON "CaseArtwork" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseartwork_delete" ON "CaseArtwork";
CREATE POLICY "caseartwork_delete" ON "CaseArtwork" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CaseEvidence
-- ----------------------------------------------------------------------
ALTER TABLE "CaseEvidence" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "caseevidence_select" ON "CaseEvidence";
CREATE POLICY "caseevidence_select" ON "CaseEvidence" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseevidence_insert" ON "CaseEvidence";
CREATE POLICY "caseevidence_insert" ON "CaseEvidence" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseevidence_update" ON "CaseEvidence";
CREATE POLICY "caseevidence_update" ON "CaseEvidence" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseevidence_delete" ON "CaseEvidence";
CREATE POLICY "caseevidence_delete" ON "CaseEvidence" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- EvidenceClaim
-- ----------------------------------------------------------------------
ALTER TABLE "EvidenceClaim" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "evidenceclaim_select" ON "EvidenceClaim";
CREATE POLICY "evidenceclaim_select" ON "EvidenceClaim" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidenceclaim_insert" ON "EvidenceClaim";
CREATE POLICY "evidenceclaim_insert" ON "EvidenceClaim" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidenceclaim_update" ON "EvidenceClaim";
CREATE POLICY "evidenceclaim_update" ON "EvidenceClaim" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidenceclaim_delete" ON "EvidenceClaim";
CREATE POLICY "evidenceclaim_delete" ON "EvidenceClaim" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ClaimAssessment
-- ----------------------------------------------------------------------
ALTER TABLE "ClaimAssessment" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "claimassessment_select" ON "ClaimAssessment";
CREATE POLICY "claimassessment_select" ON "ClaimAssessment" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claimassessment_insert" ON "ClaimAssessment";
CREATE POLICY "claimassessment_insert" ON "ClaimAssessment" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claimassessment_update" ON "ClaimAssessment";
CREATE POLICY "claimassessment_update" ON "ClaimAssessment" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "claimassessment_delete" ON "ClaimAssessment";
CREATE POLICY "claimassessment_delete" ON "ClaimAssessment" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ArtworkParty
-- ----------------------------------------------------------------------
ALTER TABLE "ArtworkParty" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artworkparty_select" ON "ArtworkParty";
CREATE POLICY "artworkparty_select" ON "ArtworkParty" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkparty_insert" ON "ArtworkParty";
CREATE POLICY "artworkparty_insert" ON "ArtworkParty" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkparty_update" ON "ArtworkParty";
CREATE POLICY "artworkparty_update" ON "ArtworkParty" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkparty_delete" ON "ArtworkParty";
CREATE POLICY "artworkparty_delete" ON "ArtworkParty" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- CaseParty
-- ----------------------------------------------------------------------
ALTER TABLE "CaseParty" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "caseparty_select" ON "CaseParty";
CREATE POLICY "caseparty_select" ON "CaseParty" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseparty_insert" ON "CaseParty";
CREATE POLICY "caseparty_insert" ON "CaseParty" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseparty_update" ON "CaseParty";
CREATE POLICY "caseparty_update" ON "CaseParty" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "caseparty_delete" ON "CaseParty";
CREATE POLICY "caseparty_delete" ON "CaseParty" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- EvidenceSource
-- ----------------------------------------------------------------------
ALTER TABLE "EvidenceSource" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "evidencesource_select" ON "EvidenceSource";
CREATE POLICY "evidencesource_select" ON "EvidenceSource" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidencesource_insert" ON "EvidenceSource";
CREATE POLICY "evidencesource_insert" ON "EvidenceSource" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidencesource_update" ON "EvidenceSource";
CREATE POLICY "evidencesource_update" ON "EvidenceSource" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "evidencesource_delete" ON "EvidenceSource";
CREATE POLICY "evidencesource_delete" ON "EvidenceSource" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ArtworkExhibition
-- ----------------------------------------------------------------------
ALTER TABLE "ArtworkExhibition" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artworkexhibition_select" ON "ArtworkExhibition";
CREATE POLICY "artworkexhibition_select" ON "ArtworkExhibition" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkexhibition_insert" ON "ArtworkExhibition";
CREATE POLICY "artworkexhibition_insert" ON "ArtworkExhibition" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkexhibition_update" ON "ArtworkExhibition";
CREATE POLICY "artworkexhibition_update" ON "ArtworkExhibition" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkexhibition_delete" ON "ArtworkExhibition";
CREATE POLICY "artworkexhibition_delete" ON "ArtworkExhibition" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ArtworkPublication
-- ----------------------------------------------------------------------
ALTER TABLE "ArtworkPublication" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artworkpublication_select" ON "ArtworkPublication";
CREATE POLICY "artworkpublication_select" ON "ArtworkPublication" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkpublication_insert" ON "ArtworkPublication";
CREATE POLICY "artworkpublication_insert" ON "ArtworkPublication" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkpublication_update" ON "ArtworkPublication";
CREATE POLICY "artworkpublication_update" ON "ArtworkPublication" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "artworkpublication_delete" ON "ArtworkPublication";
CREATE POLICY "artworkpublication_delete" ON "ArtworkPublication" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Artist
-- ----------------------------------------------------------------------
ALTER TABLE "Artist" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artist_select" ON "Artist";
CREATE POLICY "artist_select" ON "Artist" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("approved" = true))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("approved" = true))
);

DROP POLICY IF EXISTS "artist_insert" ON "Artist";
CREATE POLICY "artist_insert" ON "Artist" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "artist_update" ON "Artist";
CREATE POLICY "artist_update" ON "Artist" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("userId" = nullif(current_setting('qhakaza.user_id', true), '')))
);

DROP POLICY IF EXISTS "artist_delete" ON "Artist";
CREATE POLICY "artist_delete" ON "Artist" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- Artwork
-- ----------------------------------------------------------------------
ALTER TABLE "Artwork" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "artwork_select" ON "Artwork";
CREATE POLICY "artwork_select" ON "Artwork" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("status" = 'PUBLISHED' AND "artistId" IN (SELECT "id" FROM "Artist" WHERE "approved" = true)))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("status" = 'PUBLISHED' AND "artistId" IN (SELECT "id" FROM "Artist" WHERE "approved" = true)))
);

DROP POLICY IF EXISTS "artwork_insert" ON "Artwork";
CREATE POLICY "artwork_insert" ON "Artwork" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "artwork_update" ON "Artwork";
CREATE POLICY "artwork_update" ON "Artwork" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("artistId" IN (SELECT "id" FROM "Artist" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "artwork_delete" ON "Artwork";
CREATE POLICY "artwork_delete" ON "Artwork" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- NewsArticle
-- ----------------------------------------------------------------------
ALTER TABLE "NewsArticle" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "newsarticle_select" ON "NewsArticle";
CREATE POLICY "newsarticle_select" ON "NewsArticle" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist' AND ("status" = 'PUBLISHED'))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("status" = 'PUBLISHED'))
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public' AND ("status" = 'PUBLISHED'))
);

DROP POLICY IF EXISTS "newsarticle_insert" ON "NewsArticle";
CREATE POLICY "newsarticle_insert" ON "NewsArticle" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "newsarticle_update" ON "NewsArticle";
CREATE POLICY "newsarticle_update" ON "NewsArticle" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "newsarticle_delete" ON "NewsArticle";
CREATE POLICY "newsarticle_delete" ON "NewsArticle" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

-- ----------------------------------------------------------------------
-- PrivateNoteSubmission
-- ----------------------------------------------------------------------
ALTER TABLE "PrivateNoteSubmission" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "privatenotesubmission_select" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_select" ON "PrivateNoteSubmission" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR (coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector' AND ("membershipId" IN (SELECT "id" FROM "Membership" WHERE "userId" = nullif(current_setting('qhakaza.user_id', true), ''))))
);

DROP POLICY IF EXISTS "privatenotesubmission_insert" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_insert" ON "PrivateNoteSubmission" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
);

DROP POLICY IF EXISTS "privatenotesubmission_update" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_update" ON "PrivateNoteSubmission" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "privatenotesubmission_delete" ON "PrivateNoteSubmission";
CREATE POLICY "privatenotesubmission_delete" ON "PrivateNoteSubmission" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- AnalyticsEvent
-- ----------------------------------------------------------------------
ALTER TABLE "AnalyticsEvent" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "analyticsevent_select" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_select" ON "AnalyticsEvent" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "analyticsevent_insert" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_insert" ON "AnalyticsEvent" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'artist'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'collector'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'public'
);

DROP POLICY IF EXISTS "analyticsevent_update" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_update" ON "AnalyticsEvent" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "analyticsevent_delete" ON "AnalyticsEvent";
CREATE POLICY "analyticsevent_delete" ON "AnalyticsEvent" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- DailyMetric
-- ----------------------------------------------------------------------
ALTER TABLE "DailyMetric" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "dailymetric_select" ON "DailyMetric";
CREATE POLICY "dailymetric_select" ON "DailyMetric" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "dailymetric_insert" ON "DailyMetric";
CREATE POLICY "dailymetric_insert" ON "DailyMetric" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "dailymetric_update" ON "DailyMetric";
CREATE POLICY "dailymetric_update" ON "DailyMetric" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "dailymetric_delete" ON "DailyMetric";
CREATE POLICY "dailymetric_delete" ON "DailyMetric" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- AuditLog
-- ----------------------------------------------------------------------
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auditlog_select" ON "AuditLog";
CREATE POLICY "auditlog_select" ON "AuditLog" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "auditlog_insert" ON "AuditLog";
CREATE POLICY "auditlog_insert" ON "AuditLog" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'analyst'
);

DROP POLICY IF EXISTS "auditlog_update" ON "AuditLog";
CREATE POLICY "auditlog_update" ON "AuditLog" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "auditlog_delete" ON "AuditLog";
CREATE POLICY "auditlog_delete" ON "AuditLog" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- ActivationAttempt
-- ----------------------------------------------------------------------
ALTER TABLE "ActivationAttempt" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activationattempt_select" ON "ActivationAttempt";
CREATE POLICY "activationattempt_select" ON "ActivationAttempt" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "activationattempt_insert" ON "ActivationAttempt";
CREATE POLICY "activationattempt_insert" ON "ActivationAttempt" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'system'
);

DROP POLICY IF EXISTS "activationattempt_update" ON "ActivationAttempt";
CREATE POLICY "activationattempt_update" ON "ActivationAttempt" FOR UPDATE USING (false);

DROP POLICY IF EXISTS "activationattempt_delete" ON "ActivationAttempt";
CREATE POLICY "activationattempt_delete" ON "ActivationAttempt" FOR DELETE USING (false);

-- ----------------------------------------------------------------------
-- Partner
-- ----------------------------------------------------------------------
ALTER TABLE "Partner" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "partner_select" ON "Partner";
CREATE POLICY "partner_select" ON "Partner" FOR SELECT USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
      OR coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'advisor'
);

DROP POLICY IF EXISTS "partner_insert" ON "Partner";
CREATE POLICY "partner_insert" ON "Partner" FOR INSERT WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partner_update" ON "Partner";
CREATE POLICY "partner_update" ON "Partner" FOR UPDATE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
) WITH CHECK (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);

DROP POLICY IF EXISTS "partner_delete" ON "Partner";
CREATE POLICY "partner_delete" ON "Partner" FOR DELETE USING (
      coalesce(nullif(current_setting('qhakaza.role', true), ''), 'public') = 'admin'
);
